#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : gcc
Version  : 12.1.0
Release  : 2616
URL      : file:///insilications/apps/gcc-12.1.0.tar.gz
Source0  : file:///insilications/apps/gcc-12.1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0-with-GCC-exception GPL-3.0+ GPL-3.0-with-GCC-exception LGPL-2.0+
Requires: gcc-doc
Requires: gcc-libubsan
Provides: cpp
Provides: cpp-symlinks
Provides: g++
Provides: g++-symlinks
Provides: g77
Provides: g77-symlinks
Provides: gcc-symlinks
Provides: gcov
Provides: gfortran
Provides: gfortran-symlinks
BuildRequires : Sphinx
BuildRequires : autogen
BuildRequires : binutils-dev
BuildRequires : binutils-extras
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : dejagnu
BuildRequires : docbook-utils
BuildRequires : docbook-xml
BuildRequires : doxygen
BuildRequires : elfutils-dev
BuildRequires : expect
BuildRequires : flex
BuildRequires : gdb-dev
BuildRequires : gettext
BuildRequires : glibc-bin
BuildRequires : glibc-dev
BuildRequires : glibc-dev32
BuildRequires : glibc-doc
BuildRequires : glibc-extras
BuildRequires : glibc-lib-avx2
BuildRequires : glibc-libc32
BuildRequires : glibc-locale
BuildRequires : glibc-nscd
BuildRequires : glibc-staticdev
BuildRequires : glibc-utils
BuildRequires : gmp-dev
BuildRequires : gmp-dev32
BuildRequires : gmp-staticdev
BuildRequires : gmp-staticdev32
BuildRequires : graphviz
BuildRequires : grep
BuildRequires : guile
BuildRequires : libc6
BuildRequires : libedit
BuildRequires : libedit-dev
BuildRequires : libffi-dev
BuildRequires : libffi-staticdev
BuildRequires : libstdc++
BuildRequires : libunwind-dev
BuildRequires : libxml2-dev
BuildRequires : libxml2-staticdev
BuildRequires : libxslt
BuildRequires : mpc-dev
BuildRequires : mpfr-dev
BuildRequires : ncurses-dev
BuildRequires : perl
BuildRequires : pkgconfig(zlib)
BuildRequires : procps-ng
BuildRequires : procps-ng-dev
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : sed
BuildRequires : tcl
BuildRequires : texinfo
BuildRequires : util-linux
BuildRequires : valgrind-dev
BuildRequires : xz-dev
BuildRequires : xz-staticdev
BuildRequires : yaml
BuildRequires : yaml-cpp
BuildRequires : zlib-dev
BuildRequires : zlib-dev32
BuildRequires : zlib-staticdev
BuildRequires : zstd-dev
BuildRequires : zstd-dev32
BuildRequires : zstd-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-optimize.patch
Patch2: 0002-vectorize.patch
Patch3: 0003-gomp-relax.patch
Patch4: 0004-avx512-when-we-ask-for-it.patch
Patch5: 0005-arch-native-override.patch
Patch6: 0006-Ignore-Werror-if-GCC_IGNORE_WERROR-envvar-set.patch
Patch7: 0007-Always-use-z-now-when-linking-with-pie.patch
Patch8: 0008-tune-inline.patch

%description
No detailed description available

%prep
%setup -q -n gcc-12.1.0
cd %{_builddir}/gcc-12.1.0
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1
%patch8 -p1
pushd %{_builddir}
cp -a %{_builddir}/gcc-12.1.0 build-special
popd

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656113665
## altflags1f content
## altflags1
unset ASFLAGS
export CPPFLAGS="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0"
export CFLAGS="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export ASMFLAGS="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export CXXFLAGS="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fvisibility-inlines-hidden -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export FCFLAGS="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export FFLAGS="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export LDFLAGS="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export CFLAGS_FOR_TARGET="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export CXXFLAGS_FOR_TARGET="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fvisibility-inlines-hidden -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export FFLAGS_FOR_TARGET="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export FCFLAGS_FOR_TARGET="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
%global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
# export PKG_CONFIG_PATH="/usr/lib64/pkgconfig:/usr/share/pkgconfig"
# export CPATH=/usr/include
# export LIBRARY_PATH=/usr/lib64
# export PATH="/usr/bin/haswell:/usr/bin:/usr/sbin"
## altflags1f end
%define gccpath gcc-12.1.0
%define gcc_target x86_64-pc-linux-gnu

if [ ! -d "../gcc-build-static" ]; then
    mkdir ../gcc-build-static;
fi

pushd ../gcc-build-static
../%{gccpath}/configure \
    --exec-prefix=/usr \
    --includedir=/usr/include \
    --libdir=/usr/lib64 \
    --libexecdir=/usr/lib64 \
    --prefix=/usr \
    --disable-libmpx \
    --disable-libunwind-exceptions \
    --disable-multiarch \
    --disable-default-pie \
    --disable-vtable-verify \
    --disable-werror \
    --disable-bootstrap \
    --disable-cet \
    --disable-default-ssp \
    --enable-multilib \
    --enable-clocale=gnu \
    --enable-__cxa_atexit \
    --enable-gnu-indirect-function \
    --enable-languages="c,c++,fortran" \
    --enable-ld=default \
    --enable-libstdcxx-pch \
    --enable-linker-build-id \
    --enable-linux-futex \
    --enable-lto \
    --enable-plugin \
    --disable-shared \
    --enable-static \
    --without-pic \
    --enable-threads=posix \
    --with-pkgversion='Clear Linux OS for Intel Architecture' \
    --with-gcc-major-version-only \
    --with-glibc-version=2.35 \
    --with-gnu-ld \
    --with-isl \
    --with-ppl=yes \
    --with-system-zlib \
    --with-arch=skylake \
    --with-tune=skylake \
    --with-static-standard-libraries=yes \
    --with-zstd
## make_macro content
make -O -j15 V=1
popd
## make_macro end

pushd ../build-special/
## altflags1_special content
## altflags1_special
## altflags1
unset ASFLAGS
export CFLAGS="-fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export ASMFLAGS="-fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export CXXFLAGS="-fasynchronous-unwind-tables -DNDEBUG=1 -fvisibility-inlines-hidden -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export FCFLAGS="-fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export FFLAGS="-fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export LDFLAGS="-fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export CFLAGS_FOR_TARGET="-fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export CXXFLAGS_FOR_TARGET="-fasynchronous-unwind-tables -DNDEBUG=1 -fvisibility-inlines-hidden -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export FFLAGS_FOR_TARGET="-fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export FCFLAGS_FOR_TARGET="-fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
%global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
# export PKG_CONFIG_PATH="/usr/lib64/pkgconfig:/usr/share/pkgconfig"
# export CPATH=/usr/include
# export LIBRARY_PATH=/usr/lib64
# export PATH="/usr/bin/haswell:/usr/bin:/usr/sbin"
## altflags1_special end
if [ ! -d "../gcc-build-shared" ]; then
    mkdir ../gcc-build-shared;
fi

pushd ../gcc-build-shared
../build-special/configure \
    --exec-prefix=/usr \
    --includedir=/usr/include \
    --libdir=/usr/lib64 \
    --libexecdir=/usr/lib64 \
    --prefix=/usr \
    --disable-libmpx \
    --disable-libunwind-exceptions \
    --disable-multiarch \
    --disable-default-pie \
    --disable-vtable-verify \
    --disable-werror \
    --disable-bootstrap \
    --disable-cet \
    --disable-default-ssp \
    --enable-multilib \
    --enable-clocale=gnu \
    --enable-__cxa_atexit \
    --enable-gnu-indirect-function \
    --enable-languages="c,c++,fortran" \
    --enable-ld=default \
    --enable-libstdcxx-pch \
    --enable-linker-build-id \
    --enable-linux-futex \
    --enable-lto \
    --enable-plugin \
    --enable-shared \
    --with-pic \
    --enable-threads=posix \
    --with-pkgversion='Clear Linux OS for Intel Architecture' \
    --with-gcc-major-version-only \
    --with-glibc-version=2.35 \
    --with-gnu-ld \
    --with-isl \
    --with-ppl=yes \
    --with-system-zlib \
    --with-arch=skylake \
    --with-tune=skylake \
    --with-static-standard-libraries=yes \
    --with-zstd
## make_macro_special content
make -O -j15 V=1
popd
## make_macro_special end
popd

%install
export SOURCE_DATE_EPOCH=1656113665
rm -rf %{buildroot}
## altflags1_special content
## altflags1_special
## altflags1
unset ASFLAGS
export CFLAGS="-fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export ASMFLAGS="-fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export CXXFLAGS="-fasynchronous-unwind-tables -DNDEBUG=1 -fvisibility-inlines-hidden -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export FCFLAGS="-fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export FFLAGS="-fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export LDFLAGS="-fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export CFLAGS_FOR_TARGET="-fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export CXXFLAGS_FOR_TARGET="-fasynchronous-unwind-tables -DNDEBUG=1 -fvisibility-inlines-hidden -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export FFLAGS_FOR_TARGET="-fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export FCFLAGS_FOR_TARGET="-fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
%global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
# export PKG_CONFIG_PATH="/usr/lib64/pkgconfig:/usr/share/pkgconfig"
# export CPATH=/usr/include
# export LIBRARY_PATH=/usr/lib64
# export PATH="/usr/bin/haswell:/usr/bin:/usr/sbin"
## altflags1_special end
## install_macro_build_special start
# pushd ../build-special
pushd ../gcc-build-shared
%make_install

find %{buildroot}/usr/ -name libiberty.a | xargs rm -f
find %{buildroot}/usr/ -name libiberty.h | xargs rm -f
chmod 0755 %{buildroot}*/usr/lib64/libgcc_s.so.1
chmod 0755 %{buildroot}*/usr/lib32/libgcc_s.so.1

chmod a+x %{buildroot}*/usr/bin
chmod a+x %{buildroot}*/usr/lib64
find %{buildroot}*/usr/lib64 %{buildroot}/usr/lib*/gcc -name '*.so*' -print0 | xargs -r0 chmod -f 755


# This is only for gdb
mkdir -p %{buildroot}//usr/share/gdb/auto-load//usr/lib64
mkdir -p %{buildroot}//usr/share/gdb/auto-load//usr/lib32
mv %{buildroot}//usr/lib64/libstdc++.so.*-gdb.py %{buildroot}//usr/share/gdb/auto-load//usr/lib64/.
mv %{buildroot}//usr/lib32/libstdc++.so.*-gdb.py %{buildroot}//usr/share/gdb/auto-load//usr/lib32/.
popd
popd
## install_macro_build_special end
## altflags1f content
## altflags1
unset ASFLAGS
export CPPFLAGS="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0"
export CFLAGS="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export ASMFLAGS="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export CXXFLAGS="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fvisibility-inlines-hidden -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export FCFLAGS="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export FFLAGS="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export LDFLAGS="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export CFLAGS_FOR_TARGET="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export CXXFLAGS_FOR_TARGET="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fvisibility-inlines-hidden -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export FFLAGS_FOR_TARGET="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export FCFLAGS_FOR_TARGET="-DGTHREAD_USE_WEAK=0 -D_GLIBCXX_GTHREAD_USE_WEAK=0 -fasynchronous-unwind-tables -DNDEBUG=1 -fno-lto -Wa,-mrelax-relocations=yes -g3 -grecord-gcc-switches -O3 -mno-vzeroupper -march=skylake -mtune=skylake -mavx -mavx2 -msse2avx -Wall -Wl,--as-needed -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000 -mprefer-vector-width=256 -falign-functions=32 -floop-nest-optimize -floop-block -fno-semantic-interposition -fno-plt -Wl,-Bsymbolic-functions -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flive-range-shrinkage -pipe -ffat-lto-objects -Wl,--build-id=sha1 -fno-reorder-blocks-and-partition -Wl,--emit-relocs -Wno-inline"
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
%global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
# export PKG_CONFIG_PATH="/usr/lib64/pkgconfig:/usr/share/pkgconfig"
# export CPATH=/usr/include
# export LIBRARY_PATH=/usr/lib64
# export PATH="/usr/bin/haswell:/usr/bin:/usr/sbin"
## altflags1f end
## install_macro start
%define gccpath gcc-12.1.0
%define gcc_target x86_64-pc-linux-gnu

pushd ../gcc-build-static
%make_install

if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
    pushd %{buildroot}/usr/lib32/pkgconfig
    for i in *.pc ; do ln -s $i 32$i ; done
    popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
    pushd %{buildroot}/usr/share/pkgconfig
    for i in *.pc ; do ln -s $i 32$i ; done
    popd
fi

cd -

cd %{buildroot}/usr/bin
if [ -e x86_64-pc-linux-gnu-g77 ]; then
    ln -sf x86_64-pc-linux-gnu-g77 g77 || true
    ln -sf g77 f77 || true
fi
if [ -e x86_64-pc-linux-gnu-gfortran ]; then
    ln -sf x86_64-pc-linux-gnu-gfortran gfortran || true
    ln -sf gfortran f95 || true
fi
ln -sf x86_64-pc-linux-gnu-g++ g++
ln -sf x86_64-pc-linux-gnu-gcc gcc
#ln -sf x86_64-pc-linux-gnu-cpp cpp
install -d %{buildroot}/usr/lib
ln -sf ../bin/cpp %{buildroot}/usr/lib/cpp
ln -sf g++ c++
ln -sf gcc cc
cd -

# This conflicts with golang, stash away
# We use gccgo to build golang
# mkdir -p %{buildroot}/usr/libexec/gccgo/bin
# mv %{buildroot}/usr/bin/go %{buildroot}/usr/libexec/gccgo/bin
# mv %{buildroot}/usr/bin/gofmt %{buildroot}/usr/libexec/gccgo/bin

find %{buildroot}/usr/ -name libiberty.a | xargs rm -f
find %{buildroot}/usr/ -name libiberty.h | xargs rm -f
# chmod 0755 %{buildroot}*/usr/lib64/libgcc_s.so.1
# chmod 0755 %{buildroot}*/usr/lib32/libgcc_s.so.1

chmod a+x %{buildroot}*/usr/bin
chmod a+x %{buildroot}*/usr/lib64
find %{buildroot}*/usr/lib64 %{buildroot}/usr/lib*/gcc -name '*.o' -print0 | xargs -r0 chmod -f 644


# This is only for gdb
# mkdir -p %{buildroot}//usr/share/gdb/auto-load//usr/lib64
# mkdir -p %{buildroot}//usr/share/gdb/auto-load//usr/lib32
# mv %{buildroot}//usr/lib64/libstdc++.so.*-gdb.py %{buildroot}//usr/share/gdb/auto-load//usr/lib64/.
# mv %{buildroot}//usr/lib32/libstdc++.so.*-gdb.py %{buildroot}//usr/share/gdb/auto-load//usr/lib32/.

# merge the two C++ include trees (needed for Clang)
pushd %{buildroot}/usr/include/c++/*/x86_64-pc-linux-gnu
find -type f \! -path ./32/\* | while read f; do
    cmp -s $f 32/$f && continue
    (
        echo '#ifdef __LP64__'
        cat $f
        echo '#else'
        cat 32/$f
        echo '#endif'
    ) > rpm-tmp-hdr
    mv rpm-tmp-hdr $f
done
for f in ./32/*; do
  rm -rf $f
  ln -s ../$(basename $f) $f
done
popd

# Also clang compat
(cd %{buildroot}/usr/lib64 && ln -s -t . gcc/x86_64-pc-linux-gnu/*/*.[ao])
(cd %{buildroot}/usr/lib32 && ln -s -t . ../lib64/gcc/x86_64-pc-linux-gnu/*/32/*.[ao])
## install_macro end
## custom find_lang start
%find_lang cpplib
%find_lang gcc
%find_lang libstdc++
mv gcc.lang tmp.lang
cat *.lang > gcc.lang
rm tmp.lang
## custom find_lang end

%files
%defattr(-,root,root,-)
